// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc_0QUzv1jhGYtt2_FcBy-OftwBAr8Wmo',
    appId: '1:133318421935:web:0a10912c75955be18dd35a',
    messagingSenderId: '133318421935',
    projectId: 'money-fllllos',
    authDomain: 'money-fllllos.firebaseapp.com',
    databaseURL: 'https://money-fllllos-default-rtdb.firebaseio.com',
    storageBucket: 'money-fllllos.firebasestorage.app',
    measurementId: 'G-J79ZS54DLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB50bJt0efVZoyxFyj5ddfjspqmGcvQ5fs',
    appId: '1:133318421935:android:c006ba485d216ce28dd35a',
    messagingSenderId: '133318421935',
    projectId: 'money-fllllos',
    databaseURL: 'https://money-fllllos-default-rtdb.firebaseio.com',
    storageBucket: 'money-fllllos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACtcBXh-l7mXEFEsqCeZpp0jfhmqL0JMM',
    appId: '1:133318421935:ios:131380e0668be9118dd35a',
    messagingSenderId: '133318421935',
    projectId: 'money-fllllos',
    databaseURL: 'https://money-fllllos-default-rtdb.firebaseio.com',
    storageBucket: 'money-fllllos.firebasestorage.app',
    iosBundleId: 'com.example.moneyBravoNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACtcBXh-l7mXEFEsqCeZpp0jfhmqL0JMM',
    appId: '1:133318421935:ios:131380e0668be9118dd35a',
    messagingSenderId: '133318421935',
    projectId: 'money-fllllos',
    databaseURL: 'https://money-fllllos-default-rtdb.firebaseio.com',
    storageBucket: 'money-fllllos.firebasestorage.app',
    iosBundleId: 'com.example.moneyBravoNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc_0QUzv1jhGYtt2_FcBy-OftwBAr8Wmo',
    appId: '1:133318421935:web:06c1d5880990a8ad8dd35a',
    messagingSenderId: '133318421935',
    projectId: 'money-fllllos',
    authDomain: 'money-fllllos.firebaseapp.com',
    databaseURL: 'https://money-fllllos-default-rtdb.firebaseio.com',
    storageBucket: 'money-fllllos.firebasestorage.app',
    measurementId: 'G-V9VYFTNRDP',
  );
}
